language: python
python:
  - "3.6"

services:
  - docker

before_script: [
    pip install docker-compose,
    docker-compose build
                 ]

script:
  - docker-compose run app sh -c "bash ./wait-for-postgres.sh db 5432 python manage.py test && flake8"